# This workflow will do a clean install of node dependencies, build the source code, and push the resulting image to the Azure Container Repository

name: ACR Docker Image CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login -u ${{ secrets.ACR_USERNAME }} --password-stdin ${{ secrets.ACR_URI }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.ACR_URI }}/digital_marketplace:test
    - name: Push the latest Docker image
      run: docker push ${{ secrets.ACR_URI }}/digital_marketplace:test
