# This workflow will do a clean install of node dependencies, build the source code, and push the resulting image to the Azure Container Repository

name: Build and Deploy to TEST

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: test
    - name: Login to ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login -u ${{ secrets.ACR_USERNAME }} --password-stdin ${{ secrets.ACR_URI }}
    - name: Build the latest Docker image
      run: docker build . --build-arg PATH_PREFIX=test-digital-marketplace --file Dockerfile --tag ${{ secrets.ACR_URI }}/digital_marketplace_test:latest
    - name: Push the latest Docker image
      run: docker push ${{ secrets.ACR_URI }}/digital_marketplace_test:latest
